services:
  - type: web
    name: apsales-torque-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn apsales.wsgi
    plan: free
    autoDeploy: true
